#pragma once

#ifdef _MSC_VER
	#define UNKNOWN_ENGINE_PRETTY_FUNCTION __FUNCSIG__
#elseif __GNUC__
	#define UNKNOWN_ENGINE_PRETTY_FUNCTION __PRETTY_FUNCTION__
#elseif __MINGW32__
	#define UNKNOWN_ENGINE_PRETTY_FUNCTION __PRETTY_FUNCTION__
#elseif __clang__
	#define UNKNOWN_ENGINE_PRETTY_FUNCTION __PRETTY_FUNCTION__
#else
	#define UNKNOWN_ENGINE_PRETTY_FUNCTION __func__
#endif
